version: "3.1"
services:
  db:
    image: grossradomir/currency_exchange:db
    container_name: currency_db
    ports:
      - "5432:5432"
    networks:
      - currency_network

  backend:
    image: grossradomir/currency_exchange:backend-1.3
    container_name: currency_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - currency_network

  frontend:
    image: grossradomir/currency_exchange:frontend-1.3
    container_name: currency_frontend
    ports:
      - "80:80"
    environment:
      - API_HOST=http://176.113.82.42:8080
    networks:
      - currency_network

networks:
  currency_network:
    driver: bridge